extends Dialogue

func _init().("lesb_wolf_greenhaven"):
	fade()
	setBackground("res://assets/Maps/Greenhaven/GreenhavenBackground.png")
	show("Queen", "left")
	talk("Queen", "Layla! Are you there?", "Sad")
	show("Layla", "right")
	talk("Layla", "Queen! Over here.", "Happy")
	talk("Queen", "You need our help?", "Neutral")
	show("Queen", "left", "Surprise")
	talk("Layla", "Yes! I need to be fucked with a strap on cus I'm a lesbian and guys suck.", "Angry")
	talk("Queen", "That is all?", "Sad")
	talk("Layla", "Yes...", "Sad")
	show("Suki", "left")
	talk("Suki", "Can I handle this?", "Happy")
	show("Queen", "right")
	talk("Queen", "Sure...", "Unimpressed")
	talk("Queen", "I will be waiting in Easthollow.", "Happy")
	show("Layla", "right")
	talk("Suki", "Ok!", "Happy")
	talk("Layla", "So...", "Seduce")
	talk("Suki", "Wait here! I will bring some toys.", "Seduce")
	fade()
	hide("Layla")
	talk("Suki", "Oh, I'm so dumb... I have none.", "Surprise")
	talk("Suki", "Maybe Queen have some at home?", "Neutral")
	
	completeQuest("lesb_wolf_greenhaven")
